name: 'Continuous integration'
on: ['push', 'pull_request']
jobs:
  php-cs:
    runs-on: 'ubuntu-latest'
    name: 'PHP coding style'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '7.4'
          extensions: 'json, mbstring, tokenizer'
          tools: 'cs2pr, php-cs-fixer:2.16.4'
        env:
          update: true

      - name: 'Check coding style'
        run: 'php-cs-fixer fix --diff --dry-run --using-cache=false --format=checkstyle | cs2pr'

  phpstan:
    name: 'PHP static analysis'
    runs-on: '${{ matrix.operating-system }}'
    strategy:
      matrix:
        php-version:
          - '7.4'
        operating-system: ['ubuntu-latest']
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'

      - name: 'Setup PHP'
        uses: 'shivammathur/setup-php@v2'
        with:
          php-version: '${{ matrix.php-version }}'
          extensions: 'json, mbstring, tokenizer'
          tools: 'composer:2'
        env:
          update: true

      - name: 'Cache composer dependencies'
        uses: 'actions/cache@v2'
        with:
          path: '~/.composer/cache'
          key: "php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}"
          restore-keys: 'php-${{ matrix.php-version }}-composer-'

      - name: 'Install composer dependencies'
        run: 'composer update --no-interaction --no-progress --no-suggest --ignore-platform-reqs'

      - name: 'Run static analysis'
        run: 'vendor/bin/phpstan analyse --configuration phpstan.neon --level 6 .'
